server:
  port: 8080

#自定义配置
my:
  #心情语录
  mood:
    today: 周五
    content: 想放假
    author: 学生

  #功能开关
  feature:
    helloSwitch: false # true = 开放接口， false = 关闭接口
    closeMsg: “接口正在维护中，请稍后再试^x^” # 接口关闭提示语

cry:
  sms:
    ccp:
      serverIP: app.cloopen.com
      port: 8883
      accountSid: 2c94811c9860a9c4019917befa1a1e22
      accountToken: a6b6a06ce294491c8895daf4e4f4341e
      appId: 2c94811c9860a9c4019917befb8f1e29
      templateId: 1