server:
  port: 8080


team:
  name: web2班
  leader: Mike
  phone: "15651078712"
  age: ${random.int(1,4)}




  spring:
    servlet:
      multipart:
          max-file-size: 10MB
          max-request-size: 100MB